In [1]:
import tensorflow as tf

In [2]:
z = tf.constant(5.2, name="z", dtype=tf.float32)
z1 = tf.constant(6.2, name="z1", dtype=tf.float32)

In [3]:
res=tf.Variable(tf.add(z,z1),name='res')

In [4]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print (sess.run(res))
print (res)

11.4
<tf.Variable 'res:0' shape=() dtype=float32_ref>


In [5]:
z2 = tf.constant(500, name="z2", dtype=tf.float32)

# Variables are used to store the state of a graph. Variables need a value to be initialized while declaring it.

In [6]:
res1=tf.Variable(tf.add(z,z2),name='res1')
res2=tf.Variable(tf.add(z,res1),name='res2')

In [7]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print (sess.run(res1))
    print (sess.run(res2))
print (res1,res2)

505.2
510.4
<tf.Variable 'res1:0' shape=() dtype=float32_ref> <tf.Variable 'res2:0' shape=() dtype=float32_ref>


In [8]:
ta1=[1,2,3,4,5]
t1=tf.convert_to_tensor(ta1,dtype=tf.float64)
ta2=[1,2,3,4,5]
t2=tf.convert_to_tensor(ta2,dtype=tf.float64)

In [10]:
with tf.Session() as sess:
    print(sess.run(t1))
    print(sess.run(t2))
    print (sess.run(tf.add(ta1,ta2)))
   

[ 1.  2.  3.  4.  5.]
[ 1.  2.  3.  4.  5.]
[ 2  4  6  8 10]


# Placeholders are used to feed external data into a TensorFlow graph. It allows a value to be assigned later i.e. a place in the memory where we’ll store a value later on.

In [11]:
ph1=tf.placeholder(name='ph1',dtype=tf.int64)
ph2=tf.placeholder(name='ph2',dtype=tf.int64)

In [12]:
v1=tf.add(ph1,ph2)

In [13]:
with tf.Session() as sess:
    print(sess.run(v1,{ph1:10,ph2:20}))

30


In [14]:
z=tf.multiply(z,z1)

In [15]:
with tf.Session() as sess:
    print(sess.run(z))

32.24


In [22]:
with tf.Session() as sess:
    print(sess.run(z1))

6.2


# the initialization of a constant should be with a value, not with operation

In [23]:
z3 = tf.constant(tf.multiply(z,z1), name="z3", dtype=tf.float32)

TypeError: Expected float32, got list containing Tensors of type '_Message' instead.

In [24]:
z3 = tf.constant(123.4, name="z3", dtype=tf.float32)

# Matrix Multiplication

In [26]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])

In [27]:
pro_mat_1_2 = tf.matmul(matrix1,matrix2)

In [28]:
with tf.Session() as sess:
    print(sess.run(pro_mat_1_2))

[[ 12.]]


In [31]:
m1 = tf.constant([[0,1,2,3,4]])
m2 = tf.constant([[0],[1],[2],[3],[4]])

In [32]:
m3 = tf.matmul(m1,m2)

In [33]:
with tf.Session() as sess:
    print(sess.run(m3))

[[30]]


In [37]:
m4= tf.matmul(m2,m1)

In [38]:
with tf.Session() as sess:
    print(sess.run(m4))

[[ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 0  2  4  6  8]
 [ 0  3  6  9 12]
 [ 0  4  8 12 16]]
