In [1]:
import keras

Using TensorFlow backend.


In [2]:
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense

In [8]:
# Initialising the CNN
classifier = Sequential()

# Step 1 - Convolution
classifier.add(Conv2D(32, (3, 3), input_shape = (64, 64, 3), activation = 'relu'))

# Step 2 - Pooling
classifier.add(MaxPooling2D(pool_size = (2, 2)))

# Adding a second convolutional layer
classifier.add(Conv2D(32, (3, 3), activation = 'relu'))
classifier.add(MaxPooling2D(pool_size = (2, 2)))

# Step 3 - Flattening
classifier.add(Flatten())

# Step 4 - Full connection
classifier.add(Dense(units = 128, activation = 'relu'))
classifier.add(Dense(units = 6, activation = 'sigmoid'))

# Compiling the CNN
classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])


In [9]:
from keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)

test_datagen = ImageDataGenerator(rescale = 1./255)


In [10]:
training_set = train_datagen.flow_from_directory('/Users/GGS/Desktop/25Nov18/ML/images_data/Cat_images/Train',
                                                 target_size = (64, 64),
                                                 batch_size = 32,
                                                 class_mode = 'categorical')


Found 1031 images belonging to 6 classes.


In [11]:
test_set = test_datagen.flow_from_directory('/Users/GGS/Desktop/25Nov18/ML/images_data/Cat_images/Test',
                                            target_size = (64, 64),
                                            batch_size = 32,
                                            class_mode = 'categorical')

Found 140 images belonging to 6 classes.


In [12]:
classifier.fit_generator(training_set,
                         steps_per_epoch = 80,
                         epochs = 20,
                         validation_data = test_set,
                         validation_steps = 80)

Epoch 1/20
80/80 [==============================] - 49s 607ms/step - loss: 0.8855 - acc: 0.7653 - val_loss: 1.2106 - val_acc: 0.3929
Epoch 2/20
80/80 [==============================] - 27s 338ms/step - loss: 0.4906 - acc: 0.8239 - val_loss: 0.8216 - val_acc: 0.6571
Epoch 3/20
80/80 [==============================] - 28s 347ms/step - loss: 0.3498 - acc: 0.8767 - val_loss: 0.6767 - val_acc: 0.7000
Epoch 4/20
80/80 [==============================] - 27s 341ms/step - loss: 0.2934 - acc: 0.8923 - val_loss: 0.4389 - val_acc: 0.8214
Epoch 5/20
80/80 [==============================] - 31s 389ms/step - loss: 0.2391 - acc: 0.9035 - val_loss: 0.4205 - val_acc: 0.8357
Epoch 6/20
80/80 [==============================] - 121s 2s/step - loss: 0.1818 - acc: 0.9387 - val_loss: 0.2432 - val_acc: 0.9214
Epoch 7/20
80/80 [==============================] - 35s 434ms/step - loss: 0.1824 - acc: 0.9294 - val_loss: 0.3346 - val_acc: 0.8786
Epoch 8/20
80/80 [==============================] - 31s 388ms/step - lo

In [13]:
import numpy as np
from keras.preprocessing import image
test_image = \
    image.load_img('/Users/GGS/Desktop/25Nov18/ML/images_data/Cat_images/Test/ant/image_0039.jpg'
                   , target_size=(64, 64))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = classifier.predict(test_image)

In [14]:
print (result)

[[ 0.  0.  1.  0.  0.  0.]]


In [15]:
import numpy as np
from keras.preprocessing import image
test_image = \
    image.load_img('/Users/GGS/Desktop/25Nov18/ML/images_data/Cat_images/Test/bass/image_0005.jpg'
                   , target_size=(64, 64))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = classifier.predict(test_image)

In [16]:
print (result)

[[ 0.  0.  0.  0.  1.  0.]]


In [19]:
import numpy as np
from keras.preprocessing import image
test_image = \
    image.load_img('/Users/GGS/Desktop/25Nov18/ML/images_data/Cat_images/Test/anchor/image_0005.jpg'
                   , target_size=(64, 64))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = classifier.predict(test_image)

In [20]:
print (result)

[[ 0.  1.  0.  0.  0.  0.]]


CNN:
https://www.analyticsindiamag.com/learn-image-classification-using-cnn-in-keras-with-code/
http://www.vision.caltech.edu/Image_Datasets/Caltech101/
http://www.vision.caltech.edu/Image_Datasets/Caltech101/101_ObjectCategories.tar.gz
https://github.com/rohanpillai20/Image-Classification-by-Keras-and-Tensorflow/